class AddStateFields < ActiveRecord::Migration[5.2]
  def up
    state = Field.find_or_create_by(name: 'state',
                                    input: 'select',
                                    label: 'State',
                                    global_registry_attribute: 'address.state',
                                    adobe_campaign_attribute: 'location.stateCode',
                                    placeholder: nil)

    state.option_values.clear
    state.field_options.clear

    al = OptionValue.find_or_create_by(name: "AL", label: "Alabama")
    ak = OptionValue.find_or_create_by(name: "AK", label: "Alaska")
    az = OptionValue.find_or_create_by(name: "AZ", label: "Arizona")
    ar = OptionValue.find_or_create_by(name: "AR", label: "Arkansas")
    ca = OptionValue.find_or_create_by(name: "CA", label: "California")
    co = OptionValue.find_or_create_by(name: "CO", label: "California")
    ct = OptionValue.find_or_create_by(name: "CT", label: "Connecticut")
    de = OptionValue.find_or_create_by(name: "DE", label: "Delaware")
    fl = OptionValue.find_or_create_by(name: "FL", label: "Florida")
    ga = OptionValue.find_or_create_by(name: "GA", label: "Georgia")
    hi = OptionValue.find_or_create_by(name: "HI", label: "Hawaii")
    id = OptionValue.find_or_create_by(name: "ID", label: "Idaho")
    il = OptionValue.find_or_create_by(name: "IL", label: "Illinois")
    ind = OptionValue.find_or_create_by(name: "IN", label: "Indiana")
    ia = OptionValue.find_or_create_by(name: "IA", label: "Iowa")
    ks = OptionValue.find_or_create_by(name: "KS", label: "Kansas")
    ky = OptionValue.find_or_create_by(name: "KY", label: "Kentucky")
    la = OptionValue.find_or_create_by(name: "LA", label: "Louisiana")
    me = OptionValue.find_or_create_by(name: "ME", label: "maine")
    md = OptionValue.find_or_create_by(name: "MD", label: "Maryland")
    ma = OptionValue.find_or_create_by(name: "MA", label: "Massachusetts")
    mi = OptionValue.find_or_create_by(name: "MI", label: "Michigan")
    mn = OptionValue.find_or_create_by(name: "MN", label: "Minnesota")
    ms = OptionValue.find_or_create_by(name: "MS", label: "Mississippi")
    mo = OptionValue.find_or_create_by(name: "MO", label: "Missouri")
    mt = OptionValue.find_or_create_by(name: "MT", label: "Montana")
    ne = OptionValue.find_or_create_by(name: "NE", label: "Nebraska")
    nv = OptionValue.find_or_create_by(name: "NV", label: "Nevada")
    nh = OptionValue.find_or_create_by(name: "NH", label: "New Hampire")
    nj = OptionValue.find_or_create_by(name: "NJ", label: "New Jersy")
    nm = OptionValue.find_or_create_by(name: "NM", label: "New Mexico")
    ny = OptionValue.find_or_create_by(name: "NY", label: "New York")
    nc = OptionValue.find_or_create_by(name: "NC", label: "North Carolina")
    nd = OptionValue.find_or_create_by(name: "ND", label: "North Dakota")
    oh = OptionValue.find_or_create_by(name: "OH", label: "Ohio")
    ok = OptionValue.find_or_create_by(name: "OK", label: "Oklahoma")
    org = OptionValue.find_or_create_by(name: "OR", label: "Oregon")
    pa = OptionValue.find_or_create_by(name: "PA", label: "Pennsylvania")
    ri = OptionValue.find_or_create_by(name: "RI", label: "Rhode Island")
    sc = OptionValue.find_or_create_by(name: "SC", label: "South Carolina")
    sd = OptionValue.find_or_create_by(name: "SD", label: "South Dakota")
    tn = OptionValue.find_or_create_by(name: "TN", label: "Tennessee")
    tx = OptionValue.find_or_create_by(name: "TX", label: "Texas")
    ut = OptionValue.find_or_create_by(name: "UT", label: "Utah")
    vt = OptionValue.find_or_create_by(name: "VT", label: "Vermont")
    va = OptionValue.find_or_create_by(name: "VA", label: "Virginia")
    wa = OptionValue.find_or_create_by(name: "WA", label: "Washington")
    wv = OptionValue.find_or_create_by(name: "WV", label: "West Virginia")
    wi = OptionValue.find_or_create_by(name: "WI", label: "Wisconsin")
    wy = OptionValue.find_or_create_by(name: "WY", label: "Wyoming")

    FieldOption.find_or_create_by(field: state, option_value: al, position: 0)
    FieldOption.find_or_create_by(field: state, option_value: ak, position: 1)
    FieldOption.find_or_create_by(field: state, option_value: az, position: 2)
    FieldOption.find_or_create_by(field: state, option_value: ar, position: 3)
    FieldOption.find_or_create_by(field: state, option_value: ca, position: 4)
    FieldOption.find_or_create_by(field: state, option_value: co, position: 5)
    FieldOption.find_or_create_by(field: state, option_value: ct, position: 6)
    FieldOption.find_or_create_by(field: state, option_value: de, position: 7)
    FieldOption.find_or_create_by(field: state, option_value: fl, position: 8)
    FieldOption.find_or_create_by(field: state, option_value: ga, position: 9)
    FieldOption.find_or_create_by(field: state, option_value: hi, position: 10)
    FieldOption.find_or_create_by(field: state, option_value: id, position: 11)
    FieldOption.find_or_create_by(field: state, option_value: il, position: 12)
    FieldOption.find_or_create_by(field: state, option_value: ind, position: 13)
    FieldOption.find_or_create_by(field: state, option_value: ia, position: 14)
    FieldOption.find_or_create_by(field: state, option_value: ks, position: 15)
    FieldOption.find_or_create_by(field: state, option_value: ky, position: 16)
    FieldOption.find_or_create_by(field: state, option_value: la, position: 17)
    FieldOption.find_or_create_by(field: state, option_value: me, position: 18)
    FieldOption.find_or_create_by(field: state, option_value: md, position: 19)
    FieldOption.find_or_create_by(field: state, option_value: ma, position: 20)
    FieldOption.find_or_create_by(field: state, option_value: mi, position: 21)
    FieldOption.find_or_create_by(field: state, option_value: mn, position: 22)
    FieldOption.find_or_create_by(field: state, option_value: ms, position: 23)
    FieldOption.find_or_create_by(field: state, option_value: mo, position: 24)
    FieldOption.find_or_create_by(field: state, option_value: mt, position: 25)
    FieldOption.find_or_create_by(field: state, option_value: ne, position: 26)
    FieldOption.find_or_create_by(field: state, option_value: nv, position: 27)
    FieldOption.find_or_create_by(field: state, option_value: nh, position: 28)
    FieldOption.find_or_create_by(field: state, option_value: nj, position: 29)
    FieldOption.find_or_create_by(field: state, option_value: nm, position: 30)
    FieldOption.find_or_create_by(field: state, option_value: ny, position: 31)
    FieldOption.find_or_create_by(field: state, option_value: nc, position: 32)
    FieldOption.find_or_create_by(field: state, option_value: nd, position: 33)
    FieldOption.find_or_create_by(field: state, option_value: oh, position: 34)
    FieldOption.find_or_create_by(field: state, option_value: ok, position: 35)
    FieldOption.find_or_create_by(field: state, option_value: org, position: 36)
    FieldOption.find_or_create_by(field: state, option_value: pa, position: 37)
    FieldOption.find_or_create_by(field: state, option_value: ri, position: 38)
    FieldOption.find_or_create_by(field: state, option_value: sc, position: 39)
    FieldOption.find_or_create_by(field: state, option_value: sd, position: 40)
    FieldOption.find_or_create_by(field: state, option_value: tn, position: 41)
    FieldOption.find_or_create_by(field: state, option_value: tx, position: 42)
    FieldOption.find_or_create_by(field: state, option_value: ut, position: 43)
    FieldOption.find_or_create_by(field: state, option_value: vt, position: 44)
    FieldOption.find_or_create_by(field: state, option_value: va, position: 45)
    FieldOption.find_or_create_by(field: state, option_value: wa, position: 46)
    FieldOption.find_or_create_by(field: state, option_value: wv, position: 47)
    FieldOption.find_or_create_by(field: state, option_value: wi, position: 48)
    FieldOption.find_or_create_by(field: state, option_value: wy, position: 49)
  end

  def down
    Field.find_by(name: 'State').delete_all
  end
end
