class AddTimeZoneField < ActiveRecord::Migration[6.1]
  def up
    timezone = Field.find_or_create_by(name: "TimeZone",
      input: "select",
      label: "TimeZone",
      global_registry_attribute: nil,
      adobe_campaign_attribute: "timeZone",
      placeholder: nil)
    TIME_ZONES.each_with_index do |(label, name), index|
      option_value = OptionValue.find_or_create_by(label: label, name: name)
      FieldOption.find_or_create_by(field: timezone, option_value: option_value, position: index)
    end
  end

  def down
    timezone = Field.find_by(name: "TimeZone")
    timezone.option_values.each { |ov| ov.destroy } # destroy_all does not work
    timezone.destroy
  end

  TIME_ZONES = [
    ["Default - none - none", "none"],
    ["(GMT-11:00) Samoa - Pacific_Samoa - Pacific/Samoa", "Pacific_Samoa"],
    ["(GMT-11:00) Greenwich Mean Time minus 11 hours - Gmt_m11 - Etc/GMT+11", "Gmt_m11"],
    ["(GMT-10:00) Hawai - Pacific_Honolulu - Pacific/Honolulu", "Pacific_Honolulu"],
    ["(GMT-10:00) Greenwich Mean Time minus 10 hours - Gmt_m10 - Etc/GMT+10", "Gmt_m10"],
    ["(GMT-09:00) Greenwich Mean Time minus 9 hours - Gmt_m9 - Etc/GMT+9", "Gmt_m9"],
    ["(GMT-09:00) Alaska - America_Anchorage - America/Anchorage", "America_Anchorage"],
    ["(GMT-08:00) Pacific (United States and Canada) - America_Los_Angeles - America/Los_Angeles", "America_Los_Angeles"],
    ["(GMT-08:00) Greenwich Mean Time minus 8 hours - Gmt_m8 - Etc/GMT+8", "Gmt_m8"],
    ["(GMT-07:00) Rocky Mountains (United States and Canada) - America_Denver - America/Denver", "America_Denver"],
    ["(GMT-07:00) Greenwich Mean Time minus 7 hours - Gmt_m7 - Etc/GMT+7", "Gmt_m7"],
    ["(GMT-07:00) Chihuahua, La Paz, Mazatlan - America_Chihuahua - America/Chihuahua", "America_Chihuahua"],
    ["(GMT-07:00) Arizona - America_Phoenix - America/Phoenix", "America_Phoenix"],
    ["(GMT-06:00) Guadalajara, Mexico, Monterrey - America_Mexico_City - America/Mexico_City", "America_Mexico_City"],
    ["(GMT-06:00) Greenwich Mean Time minus 6 hours - Gmt_m6 - Etc/GMT+6", "Gmt_m6"],
    ["(GMT-06:00) Central America - America_Regina - America/Regina", "America_Regina"],
    ["(GMT-06:00) Center (United States and Canada) - America_Chicago - America/Chicago", "America_Chicago"],
    ["(GMT-05:00) Indiana (East) - America_Indianapolis - America/Indianapolis", "America_Indianapolis"],
    ["(GMT-05:00) Greenwich Mean Time minus 5 hours - Gmt_m5 - Etc/GMT+5", "Gmt_m5"],
    ["(GMT-05:00) Est (United States and Canada) - America_New_York - America/New_York", "America_New_York"],
    ["(GMT-05:00) Bogota, Lima, Quito - America_Bogota - America/Bogota", "America_Bogota"],
    ["(GMT-04:30) Caracas - America_Caracas - America/Caracas", "America_Caracas"],
    ["(GMT-04:00) Santiago - America_Santiago - America/Santiago", "America_Santiago"],
    ["(GMT-04:00) Manaus - America_Manaus - America/Manaus", "America_Manaus"],
    ["(GMT-04:00) La Paz - America_La_Paz - America/La_Paz", "America_La_Paz"],
    ["(GMT-04:00) Greenwich Mean Time minus 4 hours - Gmt_m4 - Etc/GMT+4", "Gmt_m4"],
    ["(GMT-04:00) Cuiaba - America_Cuiaba - America/Cuiaba", "America_Cuiaba"],
    ["(GMT-04:00) Atlantic Standard Time (Canada) - America_Halifax - America/Halifax", "America_Halifax"],
    ["(GMT-04:00) Asunción - America_Asuncion - America/Asuncion", "America_Asuncion"],
    ["(GMT-03:30) Newfoundland - America_St_Johns - America/St_Johns", "America_St_Johns"],
    ["(GMT-03:00) Montevideo - America_Montevideo - America/Montevideo", "America_Montevideo"],
    ["(GMT-03:00) Greenwich Mean Time minus 3 hours - Gmt_m3 - Etc/GMT+3", "Gmt_m3"],
    ["(GMT-03:00) Greenland - America_Godthab - America/Godthab", "America_Godthab"],
    ["(GMT-03:00) Buenos Aires, Cayenne, Fortaleza - America_Buenos_Aires - America/Buenos_Aires", "America_Buenos_Aires"],
    ["(GMT-03:00) Brasi - America_Sao_Paulo - America/Sao_Paulo", "America_Sao_Paulo"],
    ["(GMT-02:00) Greenwich Mean Time minus 2 hours - Gmt_m2 - Etc/GMT+2", "Gmt_m2"],
    ["(GMT-02:00) Central-Atlantic - Atlantic_South_Georgia - Atlantic/South_Georgia", "Atlantic_South_Georgia"],
    ["(GMT-01:00) The Azores - Atlantic_Azores - Atlantic/Azores", "Atlantic_Azores"],
    ["(GMT-01:00) Greenwich Mean Time minus 1 hour - Gmt_m1 - Etc/GMT+1", "Gmt_m1"],
    ["(GMT-01:00) Cape Verde islands - Atlantic_Cape_Verde - Atlantic/Cape_Verde", "Atlantic_Cape_Verde"],
    ["(GMT) Casablanca - Africa_Casablanca - Africa/Casablanca", "Africa_Casablanca"],
    ["(GMT) Greenwich mean time - GMT - GMT", "GMT"],
    ["(GMT) Greenwich Mean Time: Dublin, Edinburgh, Lisbon, London - Europe_London - Europe/London", "Europe_London"],
    ["(GMT) Monrovia - Africa_Monrovia - Africa/Monrovia", "Africa_Monrovia"],
    ["(GMT) Reykjavik - Atlantic_Reykjavik - Atlantic/Reykjavik", "Atlantic_Reykjavik"],
    ["(GMT+01:00) Amsterdam, Berlin, Berne, Rome, Stockholm, Vienna - Europe_Berlin - Europe/Berlin", "Europe_Berlin"],
    ["(GMT+01:00) Belgrade, Bratislava, Budapest, Ljubljana, Prague - Europe_Belgrade - Europe/Belgrade", "Europe_Belgrade"],
    ["(GMT+01:00) Brussels, Copenhagen, Madrid, Paris - Europe_Paris - Europe/Paris", "Europe_Paris"],
    ["(GMT+01:00) Central Africa - West - Africa_Luanda - Africa/Luanda", "West"],
    ["(GMT+01:00) Greenwich Mean Time plus 1 hour - Gmt_p1 - Etc/GMT-1", "Gmt_p1"],
    ["(GMT+01:00) Sarajevo, Skoplje, Sofia, Warsaw, Zagreb - Europe_Sarajevo - Europe/Sarajevo", "Europe_Sarajevo"],
    ["(GMT+02:00) Amman - Asia_Amman - Asia/Amman", "Asia_Amman"],
    ["(GMT+02:00) Athens, Istanbul, Minsk - Europe_Athens - Europe/Athens", "Europe_Athens"],
    ["(GMT+02:00) Beirut - Asia_Beirut - Asia/Beirut", "Asia_Beirut"],
    ["(GMT+02:00) Bucarest - Europe_Bucharest - Europe/Bucharest", "Europe_Bucharest"],
    ["(GMT+02:00) Cairo - Africa_Cairo - Africa/Cairo", "Africa_Cairo"],
    ["(GMT+02:00) Damas - Asia_Damascus - Asia/Damascus", "Asia_Damascus"],
    ["(GMT+02:00) Greenwich Mean Time plus 2 hours - Gmt_p2 - Etc/GMT-2", "Gmt_p2"],
    ["(GMT+02:00) Harare, Pretoria - Africa_Harare - Africa/Harare", "Africa_Harare"],
    ["(GMT+02:00) Helsinki, Kiev, Riga, Sofia, Tallinn, Vilnius - Europe_Helsinki - Europe/Helsinki", "Europe_Helsinki"],
    ["(GMT+02:00) Jerusalem - Asia_Jerusalem - Asia/Jerusalem", "Asia_Jerusalem"],
    ["(GMT+02:00) Windhoek - Africa_Windhoek - Africa/Windhoek", "Africa_Windhoek"],
    ["(GMT+03:00) Bagdad - Asia_Baghdad - Asia/Baghdad", "Asia_Baghdad"],
    ["(GMT+03:00) Greenwich Mean Time plus 3 hours - Gmt_p3 - Etc/GMT-3", "Gmt_p3"],
    ["(GMT+03:00) Koweït, Riyad - Asia_Riyadh - Asia/Riyadh", "Asia_Riyadh"],
    ["(GMT+03:00) Moscow, St. Petersburg, Volgograd - Europe_Moscow - Europe/Moscow", "Europe_Moscow"],
    ["(GMT+03:00) Nairobi - Africa_Nairobi - Africa/Nairobi", "Africa_Nairobi"],
    ["(GMT+03:30) Teheran - Asia_Tehran - Asia/Tehran", "Asia_Tehran"],
    ["(GMT+04:00) Abu Dhabi, Muscat - Asia_Muscat - Asia/Muscat", "Asia_Muscat"],
    ["(GMT+04:00) Baku - Asia_Baku - Asia/Baku", "Asia_Baku"],
    ["(GMT+04:00) Caucasus, Erevan - Asia_Yerevan - Asia/Yerevan", "Asia_Yerevan"],
    ["(GMT+04:00) Greenwich Mean Time plus 4 hours - Gmt_p4 - Etc/GMT-4", "Gmt_p4"],
    ["(GMT+04:00) Port Louis - Indian_Mauritius - Indian/Mauritius", "Indian_Mauritius"],
    ["(GMT+04:00) Tbilissi - Asia_Tbilisi - Asia/Tbilisi", "Asia_Tbilisi"],
    ["(GMT+04:30) Kabul - Asia_Kabul - Asia/Kabul", "Asia_Kabul"],
    ["(GMT+05:00) Greenwich Mean Time plus 5 hours - Gmt_p5 - Etc/GMT-5", "Gmt_p5"],
    ["(GMT+05:00) Iekaterinburg - Asia_Yekaterinburg - Asia/Yekaterinburg", "Asia_Yekaterinburg"],
    ["(GMT+05:00) Islamabad, Karachi, Tachkent - Asia_Karachi - Asia/Karachi", "Asia_Karachi"],
    ["(GMT+05:30) Kolkata, Chennai, Mumbai, New Delhi - Asia_Kolkata - Asia/Kolkata", "Asia_Kolkata"],
    ["(GMT+05:30) Sri Jayawardenepura - Asia_Colombo - Asia/Colombo", "Asia_Colombo"],
    ["(GMT+05:45) Katmandu - Asia_Katmandu - Asia/Katmandu", "Asia_Katmandu"],
    ["(GMT+06:00) Astana, Dhaka - Asia_Dhaka - Asia/Dhaka", "Asia_Dhaka"],
    ["(GMT+06:00) Greenwich Mean Time plus 6 hours - Gmt_p6 - Etc/GMT-6", "Gmt_p6"],
    ["(GMT+06:00) Novossibirsk - Asia_Novosibirsk - Asia/Novosibirsk", "Asia_Novosibirsk"],
    ["(GMT+06:30) Rangoon - Asia_Rangoon - Asia/Rangoon", "Asia_Rangoon"],
    ["(GMT+07:00) Bangkok, Hanoi, Djakarta - Asia_Bangkok - Asia/Bangkok", "Asia_Bangkok"],
    ["(GMT+07:00) Greenwich Mean Time plus 7 hours - Gmt_p7 - Etc/GMT-7", "Gmt_p7"],
    ["(GMT+07:00) Krasnoïarsk - Asia_Krasnoyarsk - Asia/Krasnoyarsk", "Asia_Krasnoyarsk"],
    ["(GMT+08:00) Beijing, Chongqing, Hong Kong, Urumqi - Asia_Shanghai - Asia/Shanghai", "Asia_Shanghai"],
    ["(GMT+08:00) Greenwich Mean Time plus 8 hours - Gmt_p8 - Etc/GMT-8", "Gmt_p8"],
    ["(GMT+08:00) Irkoutsk - Asia_Irkutsk - Asia/Irkutsk", "Asia_Irkutsk"],
    ["(GMT+08:00) Kuala Lumpur, Singapore - Asia_Kuala_Lumpur - Asia/Kuala_Lumpur", "Asia_Kuala_Lumpur"],
    ["(GMT+08:00) Oulan-Bator - Asia_Ulan_Bator - Asia/Ulan_Bator", "Asia_Ulan_Bator"],
    ["(GMT+08:00) Perth - Australia_Perth - Australia/Perth", "Australia_Perth"],
    ["(GMT+08:00) Taipei - Asia_Taipei - Asia/Taipei", "Asia_Taipei"],
    ["(GMT+09:00) Greenwich Mean Time plus 9 hours - Gmt_p9 - Etc/GMT-9", "Gmt_p9"],
    ["(GMT+09:00) Osaka, Sapporo, Tokyo - Asia_Tokyo - Asia/Tokyo", "Asia_Tokyo"],
    ["(GMT+09:00) Seoul - Asia_Seoul - Asia/Seoul", "Asia_Seoul"],
    ["(GMT+09:00) Yakoutsk - Asia_Yakutsk - Asia/Yakutsk", "Asia_Yakutsk"],
    ["(GMT+09:30) Adelaïde - Australia_Adelaide - Australia/Adelaide", "Australia_Adelaide"],
    ["(GMT+09:30) Darwin - Australia_Darwin - Australia/Darwin", "Australia_Darwin"],
    ["(GMT+10:00) Brisbane - Australia_Brisbane - Australia/Brisbane", "Australia_Brisbane"],
    ["(GMT+10:00) Canberra, Melbourne, Sydney - Australia_Canberra - Australia/Canberra", "Australia_Canberra"],
    ["(GMT+10:00) Greenwich Mean Time plus 10 hours - Gmt_p10 - Etc/GMT-10", "Gmt_p10"],
    ["(GMT+10:00) Guam, Port Moresby - Pacific_Guam - Pacific/Guam", "Pacific_Guam"],
    ["(GMT+10:00) Hobart - Australia_Hobart - Australia/Hobart", "Australia_Hobart"],
    ["(GMT+10:00) Vladivostok - Asia_Vladivostok - Asia/Vladivostok", "Asia_Vladivostok"],
    ["(GMT+11:00) Greenwich Mean Time plus 11 hours - Gmt_p11 - Etc/GMT-11", "Gmt_p11"],
    ["(GMT+11:00) Magadan, The Solomon Islands, New Caledonia - Pacific_Guadalcanal - Pacific/Guadalcanal", "Pacific_Guadalcanal"],
    ["(GMT+12:00) Auckland, Wellington - Pacific_Auckland - Pacific/Auckland", "Pacific_Auckland"],
    ["(GMT+12:00) Fidji - Pacific_Fiji - Pacific/Fiji", "Pacific_Fiji"],
    ["(GMT+12:00) Greenwich Mean Time plus 12 hours - Gmt_p12 - Etc/GMT-12", "Gmt_p12"],
    ["(GMT+13:00) Greenwich Mean Time plus 13 hours - Gmt_p13 - Etc/GMT-13", "Gmt_p13"],
    ["(GMT+13:00) Nuku'alofa - Pacific_Tongatapu - Pacific/Tongatapu", "Pacific_Tongatapu"]
  ]
end
