name: Ruby

on:
  pull_request:
    branches: [master]
  push:
    branches: [master,staging]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      DB_PORT_5432_TCP_ADDR_TEST: localhost
      DB_ENV_POSTGRESQL_USER_TEST: postgres
      DB_ENV_POSTGRESQL_PASS_TEST: postgres
      DB_ENV_POSTGRESQL_DB_TEST: postgres
      RAILS_ENV: test

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_PASSWORD: postgres
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
        ports:
          - 5432:5432
      redis:
        image: redis
        options: --health-cmd "redis-cli ping" --health-interval 10s --health-timeout 5s --health-retries 5
        ports:
          - 6379:6379

    steps:
      - name: Check out files
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
        env:
          BUNDLE_GEMS__CONTRIBSYS__COM: ${{ secrets.BUNDLE_GEMS__CONTRIBSYS__COM }}

      - name: Set up DB
        run: |
          bundle exec rails db:create
          bundle exec rails db:schema:load

      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: 16.20.0

      - name: Install yarn dependencies and precompile assets
        run: bundle exec rails assets:precompile

      - name: RSpec tests
        run: bundle exec rspec --color

      - name: Codecov upload
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out files
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
        env:
          BUNDLE_GEMS__CONTRIBSYS__COM: ${{ secrets.BUNDLE_GEMS__CONTRIBSYS__COM }}

      - name: Bundle audit
        run: bundle exec bundle audit check --update ${{ vars.CVE_IGNORES && format('--ignore {0}', vars.CVE_IGNORES) }}

      - name: Brakeman
        run: bundle exec brakeman -A -q --ensure-latest --no-pager

      - name: StandardRB
        run: bundle exec standardrb --format simple

      - name: Install yarn dependencies
        run: yarn install --frozen-lockfile

      - name: Yarn audit
        run: yarn run improved-yarn-audit --ignore-dev-deps
